<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KV0K3U5" failures="21" tests="37" name="Surefire test" time="2770.03" errors="0" timestamp="02 Apr 2020 02:09:23 GMT">
  <testcase classname="testcases.HomePageTests" name="validateHomePageIconTest" time="4.303"/>
  <testcase classname="testcases.HomePageTests" name="validateNewBtnLinkTest" time="20.768"/>
  <testcase classname="testcases.HomePageTests" name="validatePageTitleTest" time="0.071">
    <failure type="java.lang.AssertionError" message="expected [[Sell Your Car!] but found [Sell Your Car!]">
      <![CDATA[java.lang.AssertionError: expected [[Sell Your Car!] but found [Sell Your Car!]
	at testcases.HomePageTests.validatePageTitleTest(HomePageTests.java:35)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validatePageTitleTest -->
  <testcase classname="testcases.HomePageTests" name="validateSearchBtnLinkTest" time="21.019"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="92.293">
    <failure type="java.lang.AssertionError" message="expected [Invalid address] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid address] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="90.594">
    <failure type="java.lang.AssertionError" message="expected [Invalid name] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid name] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="47.232">
    <failure type="java.lang.AssertionError" message="expected [Invalid city] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid city] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="21.823"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="46.069">
    <failure type="java.lang.AssertionError" message="expected [Invalid number] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid number] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="88.766">
    <failure type="java.lang.AssertionError" message="expected [Invalid number] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid number] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="77.063">
    <failure type="java.lang.AssertionError" message="expected [Invalid number] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid number] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="70.126">
    <failure type="java.lang.AssertionError" message="expected [Invalid number] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid number] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="90.454">
    <failure type="java.lang.AssertionError" message="expected [Invalid number] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid number] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="21.888"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="90.768">
    <failure type="java.lang.AssertionError" message="expected [Invalid email] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid email] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="21.932"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="21.708">
    <failure type="java.lang.AssertionError" message="expected [Invalid email] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid email] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="86.551">
    <failure type="java.lang.AssertionError" message="expected [Invalid email] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid email] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="13.362">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//div[@class=&amp;apos;main2&amp;apos;]//descendant::p[@id=&amp;quot;message&amp;quot;]&amp;quot;}
  (Session info: chrome=80.0.3987.149)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &amp;apos;3.14.0&amp;apos;, revision: &amp;apos;aacccce0&amp;apos;, time: &amp;apos;2018-08-02T20:19:58.91Z&amp;apos;
System info: host: &amp;apos;DESKTOP-KV0K3U5&amp;apos;, ip: &amp;apos;192.168.0.30&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;13.0.2&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 80.0.3987.149, chrome: {chromedriverVersion: 80.0.3987.106 (f68069574609..., userDataDir: C:\WINDOWS\TEMP\scoped_dir1...}, goog:chromeOptions: {debuggerAddress: localhost:53841}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 4ed4eb8d85c5aba817ebf9e94630e6f6
*** Element info: {Using=xpath, value=//div[@class=&amp;apos;main2&amp;apos;]//descendant::p[@id=&amp;quot;message&amp;quot;]}">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='main2']//descendant::p[@id="message"]"}
  (Session info: chrome=80.0.3987.149)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'DESKTOP-KV0K3U5', ip: '192.168.0.30', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '13.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 80.0.3987.149, chrome: {chromedriverVersion: 80.0.3987.106 (f68069574609..., userDataDir: C:\WINDOWS\TEMP\scoped_dir1...}, goog:chromeOptions: {debuggerAddress: localhost:53841}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 4ed4eb8d85c5aba817ebf9e94630e6f6
*** Element info: {Using=xpath, value=//div[@class='main2']//descendant::p[@id="message"]}
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:424)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
	at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
	at com.sun.proxy.$Proxy8.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:194)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy12.getText(Unknown Source)
	at com.qa.carreg.pages.RegistrationPage.messageDisplayed(RegistrationPage.java:95)
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="88.811">
    <failure type="java.lang.AssertionError" message="expected [Invalid year] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid year] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="82.629">
    <failure type="java.lang.AssertionError" message="expected [Invalid year] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid year] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="28.445">
    <failure type="java.lang.AssertionError" message="expected [Invalid year] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid year] but found []
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="21.992">
    <failure type="java.lang.AssertionError" message="expected [Invalid year] but found [Invalid Year]">
      <![CDATA[java.lang.AssertionError: expected [Invalid year] but found [Invalid Year]
	at testcases.RegistrationPageTests.validateNewregistrationNegativeCases(RegistrationPageTests.java:65)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationNegativeCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="85.212"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="81.078"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="24.278"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="21.75"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="45.178"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="21.858"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="71.267"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationNegativeCases" time="24.715"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationPositiveCases" time="6.112">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testcases.RegistrationPageTests.validateNewregistrationPositiveCases(RegistrationPageTests.java:91)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationPositiveCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationPositiveCases" time="3.066"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationPositiveCases" time="3.056">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testcases.RegistrationPageTests.validateNewregistrationPositiveCases(RegistrationPageTests.java:91)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationPositiveCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationPositiveCases" time="5.44"/>
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationPositiveCases" time="23.573">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:425)
	at com.qa.carreg.pages.DisplayPage.validinputdata(DisplayPage.java:39)
	at testcases.RegistrationPageTests.validateNewregistrationPositiveCases(RegistrationPageTests.java:79)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationPositiveCases -->
  <testcase classname="testcases.RegistrationPageTests" name="validateNewregistrationPositiveCases" time="22.636">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:425)
	at com.qa.carreg.pages.DisplayPage.validinputdata(DisplayPage.java:39)
	at testcases.RegistrationPageTests.validateNewregistrationPositiveCases(RegistrationPageTests.java:79)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateNewregistrationPositiveCases -->
</testsuite> <!-- Surefire test -->
